#!/usr/bin/env sh
#Copyright (C) 2023 akquinet GmbH
 #
 #Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 #You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing,
 #software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 #See the License for the specific language governing permissions and limitations under the License.

. "$(dirname -- "$0")/_/husky.sh"

CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" { print $2}')"

if [ -z "$CHANGED_FILES" ]; then
  echo "No staged files."
  exit 0
fi;

export CI=true
printf "Trying to fix style validations automatically ...\n"
yarn fix || :
yarn test:lint

echo "$CHANGED_FILES" | while read -r file; do
  if [ -f $file ]; then
    git add $file
  fi
done